repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: [--maxkb=100]
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml

  - repo: https://github.com/psf/black.git
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.11
        args: [--line-length=120]
